### ISSUE TITLE
Define a rough roadmap?

### ISSUE THREAD

**Issue by angerman** [snowleopard/shaking-up-ghc#147]
By @ndmitchell recent tweet about the speed of shake's ghc build, and our set of issues, should we define a rough roadmap and add milestones to the project to focus on the relevant tasks to get to a certain milestone?

Say:
- [x] Milestone 0
  - [x] manage to compile `ghc` with shake.
- [ ] Milestone 1
  - [ ] Remove build products from the source tree
  - [ ] Implement Vanilla way
  - [ ] Haddock for all used functions
- [ ] Milestone 2
  - [ ] Support Threaded, Debug Ways
  - [ ] Drop ghc-cabal
- [ ] Milestone 3
  - [ ] Support Profiling, Logging, Dynamic Ways
  - [ ] Drop Perl Dependency (rewrite `ghc-split` in `Haskell`)
- [ ] Milestone 4
  - [ ] Support Parallel, and GrandSim Way

This is just a rough sketch. Let's collect more high level items to be added.
Maybe we want to give those mile stones some fancy names?

Or just tell me that this is a stupid idea :)

**Note**: *If you edit this comment directly, please leave a comment about what you did, so others are notified*

**Comment by ndmitchell** [comment]
I tend to find a ticket for each one plus milestone tags tends to work better - each item may be a considerable amount of work/discussion.

**Comment by ndmitchell** [comment]
In act, I'd just have a "required" tag and let the work flow in the order that makes sense, rather than milestoning.

**Comment by angerman** [comment]
> I tend to find a ticket for each one plus milestone tags tends to work better - each item may be a considerable amount of work/discussion.

Ohh, don't get me wrong @ndmitchell I actually meant using githubs Milestones. The checklist above was just supposed to be a general overview of how a rough roadmap could look. I think we have for most of the mentioned items already issues, hence only roadmap tickets would need to be assigned those existing issues (potentially missing issues created) and this issue could be closed then. I do **not** intend to use the above checkmark system as the actual roadmap. I didn't even know the extra features github added when one had ascii checkboxes in an issue.

> In act, I'd just have a "required" tag and let the work flow in the order that makes sense, rather than milestoning.

My idea behind the milestoning was more to the point of being able to say,
- we plan to have the following working to call this an intermediate release.
- The milestone contains x, y, and z and you can expect that to work.

As has been mentioned and noted elsewhere until the whole ghc build system
will all its intricacies is covered is going to take a **long** time.  Yet there might
be other interested parties in trying this out and having certain milestones would
(at least me) assure that I could now give the build system a try as it covers
everything I'm interested in.

I also assume that at some point this project (for it is successful) could not be a
strict subset of the old build system, but contain some additional features already
while still having to cover each and every corner case of the `make` based system.

Did I manage to make any sense?

**Comment by ndmitchell** [comment]
That all makes sense.

I suspect that if the abstractions underneath are solid then speed of new features keeps going up (unlike make where additional complexity keeps slowing you down), so it might not take as long as you think :)

**Comment by angerman** [comment]
@ndmitchell are you advocating to shoot for week based milestones, then ;-)

**Comment by snowleopard** [comment]
Thanks for bringing this up! I've been thinking about adding milestones for some time now. 

I'd like the first milestone to cover the following:
* Move build targets into a separate folder #113.
* Add a clean target #131.
* Refactor ways #100.
* Make sure `profiling` way works.
* Refactor builders #124. 
* Add a high-level overview of how the build system works #56.

Once the above is ready I will no longer be too embarrassed to release the new build system for people to try. 

Please let me know what you think of the above list. If we agree on it, I'll create a milestone and tag the relevant issues.

**Comment by ndmitchell** [comment]
That's a superset of what I'd consider essential in the first pass (all the patches marked refactor don't seem essential, neither does profiling or command line args to Settings) - but certainly no harm in doing more.

**Comment by snowleopard** [comment]
@ndmitchell The refactor patches better be done before writing an overview, because they simplify things. They are not very time consuming. I agree about `profiling` and command line args: they can be skipped if they turn out to be more difficult then I think.

**Comment by angerman** [comment]
Alright then, let's decide on Release Milestone names. Should we go with something boring like sequential numbers, or should we use some date based milestones, or some fantasy names? 

@snowleopard I'm working on that *very* high level documentation, which I hope is independent on those refactor patches.

On the question whether or not this will go directly into ghc, my impression was that we'd be external for at least the first few milestones and have people using this shake based build system as we use it right now, once a sufficient percentage of users are using the shake base build system to integrate it into ghc.

**Comment by snowleopard** [comment]
> Alright then, let's decide on Release Milestone names. Should we go with something boring like sequential numbers, or should we use some date based milestones, or some fantasy names?

@angerman Taking the name of the project into account I was thinking along these lines:
* `first-shake`: the coming initial release,
* `tree-tremble`: we become a part of the GHC tree,
* `ghc-quake`: once we can do whatever `make` can, so everyone switches over,
* etc. :)

**Comment by ndmitchell** [comment]
:+1: - nice names, and I think also the perfect milestones to have - those 3 seem perfect.

**Comment by snowleopard** [comment]
Done! I'll close this now, ticking off the first issue of the `first-shake` milestone.

@angerman Feel free to create separate issues for the tasks you listed at the top of the thread.
